/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas;

/**
 *
 * @author its18
 */
public class f2_menuDueno extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN_1
     */
    public f2_menuDueno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cuerpoContenedorMenu_D = new javax.swing.JPanel();
        iconoPuntoDeVentaMenuDueno_1 = new javax.swing.JLabel();
        iconoGestionarUsuarioMenuDueno_2 = new javax.swing.JLabel();
        iconoGestionarInventarioMenuDueno = new javax.swing.JLabel();
        iconoGenerarPreLista = new javax.swing.JLabel();
        botonPuntoDeVenta = new javax.swing.JButton();
        botonGestionarUsuario = new javax.swing.JButton();
        botonGestionarInventario = new javax.swing.JButton();
        botonPrelista = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();
        fondoMD = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENÚ DUEÑO");
        setMinimumSize(new java.awt.Dimension(1000, 500));

        cuerpoContenedorMenu_D.setMinimumSize(new java.awt.Dimension(1000, 500));
        cuerpoContenedorMenu_D.setPreferredSize(new java.awt.Dimension(1000, 500));
        cuerpoContenedorMenu_D.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconoPuntoDeVentaMenuDueno_1.setBackground(new java.awt.Color(255, 255, 255));
        iconoPuntoDeVentaMenuDueno_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/D)iconoPuntoDeVentaMenuDueno_1.png"))); // NOI18N
        cuerpoContenedorMenu_D.add(iconoPuntoDeVentaMenuDueno_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 130, 30, 40));

        iconoGestionarUsuarioMenuDueno_2.setBackground(new java.awt.Color(255, 255, 255));
        iconoGestionarUsuarioMenuDueno_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/E)iconoGestionarUsuarioMenuDueno_2.png"))); // NOI18N
        cuerpoContenedorMenu_D.add(iconoGestionarUsuarioMenuDueno_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, 40));

        iconoGestionarInventarioMenuDueno.setBackground(new java.awt.Color(255, 255, 255));
        iconoGestionarInventarioMenuDueno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/F)iconoGestionarInventarioMenuDueno_3.png"))); // NOI18N
        cuerpoContenedorMenu_D.add(iconoGestionarInventarioMenuDueno, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 30, 40));

        iconoGenerarPreLista.setBackground(new java.awt.Color(255, 255, 255));
        iconoGenerarPreLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/G)iconoGenerarPreListaMenuDueno_4.png"))); // NOI18N
        cuerpoContenedorMenu_D.add(iconoGenerarPreLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, -1, 40));

        botonPuntoDeVenta.setBackground(new java.awt.Color(69, 100, 123));
        botonPuntoDeVenta.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        botonPuntoDeVenta.setText("PUNTO DE VENTA");
        botonPuntoDeVenta.setBorder(null);
        botonPuntoDeVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPuntoDeVentaActionPerformed(evt);
            }
        });
        cuerpoContenedorMenu_D.add(botonPuntoDeVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 340, 40));

        botonGestionarUsuario.setBackground(new java.awt.Color(69, 100, 123));
        botonGestionarUsuario.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        botonGestionarUsuario.setText("GESTIONAR USUARIO");
        botonGestionarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGestionarUsuarioActionPerformed(evt);
            }
        });
        cuerpoContenedorMenu_D.add(botonGestionarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 340, 40));

        botonGestionarInventario.setBackground(new java.awt.Color(69, 100, 123));
        botonGestionarInventario.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        botonGestionarInventario.setText("GESTIONAR INVENTARIO");
        botonGestionarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGestionarInventarioActionPerformed(evt);
            }
        });
        cuerpoContenedorMenu_D.add(botonGestionarInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 340, 40));

        botonPrelista.setBackground(new java.awt.Color(69, 100, 123));
        botonPrelista.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        botonPrelista.setText("GENERAR PRELISTA");
        botonPrelista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPrelistaActionPerformed(evt);
            }
        });
        cuerpoContenedorMenu_D.add(botonPrelista, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 340, 40));

        botonRegresar.setBackground(new java.awt.Color(40, 64, 72));
        botonRegresar.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        botonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        botonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/H)iconoBotonLogoutMenuDueno_5.png"))); // NOI18N
        botonRegresar.setText("CERRAR SESIÓN");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        cuerpoContenedorMenu_D.add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 200, 40));

        fondoMD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/2)fondoPantallaMenu_D.jpeg"))); // NOI18N
        fondoMD.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        fondoMD.setMaximumSize(new java.awt.Dimension(1000, 500));
        fondoMD.setMinimumSize(new java.awt.Dimension(1000, 500));
        fondoMD.setPreferredSize(new java.awt.Dimension(1000, 500));
        cuerpoContenedorMenu_D.add(fondoMD, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cuerpoContenedorMenu_D, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cuerpoContenedorMenu_D, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonGestionarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestionarUsuarioActionPerformed
        new f5_gestionarUsuario().setVisible(true);
                   dispose();
    }//GEN-LAST:event_botonGestionarUsuarioActionPerformed

    private void botonPuntoDeVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPuntoDeVentaActionPerformed
         new f3_puntoDeVenta().setVisible(true);
                   dispose();
    }//GEN-LAST:event_botonPuntoDeVentaActionPerformed

    private void botonPrelistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPrelistaActionPerformed
        new f7_generarPreLista().setVisible(true);
                   dispose();
    }//GEN-LAST:event_botonPrelistaActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
       new f1_login().setVisible(true);
                   dispose();
        
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void botonGestionarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestionarInventarioActionPerformed
       new f6_gestionarInventario().setVisible(true);
                   dispose();
    }//GEN-LAST:event_botonGestionarInventarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(f2_menuDueno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(f2_menuDueno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(f2_menuDueno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(f2_menuDueno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f2_menuDueno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGestionarInventario;
    private javax.swing.JButton botonGestionarUsuario;
    private javax.swing.JButton botonPrelista;
    private javax.swing.JButton botonPuntoDeVenta;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JPanel cuerpoContenedorMenu_D;
    private javax.swing.JLabel fondoMD;
    private javax.swing.JLabel iconoGenerarPreLista;
    private javax.swing.JLabel iconoGestionarInventarioMenuDueno;
    private javax.swing.JLabel iconoGestionarUsuarioMenuDueno_2;
    private javax.swing.JLabel iconoPuntoDeVentaMenuDueno_1;
    // End of variables declaration//GEN-END:variables
}
